language: cpp

compiler:
    - clang

os: linux
install: true
script: mkdir build && make pomo

notifications:
    email:
        on_success: never
        on_failure: never

before_script:
    - dpkg -L libstdc++-6-dev

addons:
    apt:
        sources:
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test
        packages:
            - libstdc++-6-dev
